services:
  insurance-agentic-backend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.backend
    image: insurance-agentic-backend:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: insurance-agentic-backend
  insurance-agentic-frontend:
    build:
      context: .
      no_cache: true
      dockerfile: Dockerfile.frontend
    image: insurance-agentic-frontend:latest
    ports:
      - "8000:8000"
    restart: always
    container_name: insurance-agentic-frontend